### PR TITLE
Add stats for ActiveSupport cache reads.

### PR DESCRIPTION
**Pull request by roelbondoc**

### CODE REVIEW

**Comment by kevinjalbert** [comment]
I wouldn't mind seeing the corresponding specs which cover the newly added event handler and notification (in a similar fashion to how the _sql_ and *process_action( ones are handled). Looks good otherwise.

Another thing I am not too sure on at the moment is whether we should show the `cache_read_count` if the value is 0. Reason being some rails applications might not have a cache, and thus this value is 'always' zero. Although always showing the value keeps it _complete_ with respect to being machine readable. This can always be addressed later anyways.

If you can remove the version bump change, as I'll manually bump it as part of my release process.

**Comment by roelbondoc** [comment]
Ah ok sure I'll update the specs.

That's a good point. I can hide that report if the value is zero if you want. Perhaps being able to configure what fields are reported might be a useful feature in the future?

Sure I'll remove the version bump. I'm not even sure how that got bumped in the first place.

**Comment by kevinjalbert** [comment]
I'm thinking it might just be fine to leave the stat in all the time with the report. If someone _really_ wanted to hide it, they have the [option](https://github.com/kevinjalbert/rails_request_stats#customizing-outputs).

**Comment by kevinjalbert** [comment]
Was thinking back on this PR, regarding _when to show the `cache_read_count`_, another option is to _opt-in_ to this stat in the report?

I've done something similar for detailed [memory stats](https://github.com/kevinjalbert/rails_request_stats#memory-stats):
1. Providing an `attr_accessor` on the `Report` class: https://github.com/kevinjalbert/rails_request_stats/blob/master/lib/rails_request_stats/report.rb#L5-L8
2. Using the `attr_accessor`, the report has the value or `nil` (which gets stripped away on the `#compact`): https://github.com/kevinjalbert/rails_request_stats/blob/master/lib/rails_request_stats/report.rb#L22-L24

---

I've done some major refactoring since this PR, so a lot of things changed. Should be easier to fit your new stat in the gem though as it'll slot into its own `Stats` class now.

**Comment by kevinjalbert** [comment]
Closing this out as I reimplemented it in #5. This was needed as a lot had changed on master.

Appreciate the help in identifying a lot of the ground work though :)

**Pull request closed without merging**
